name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build_mfes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Build
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_angular_mfe
          path: ./examples/all-templates/angular/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_preact_mfe
          path: ./examples/all-templates/preact/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_react_mfe
          path: ./examples/all-templates/react/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_solid_mfe
          path: ./examples/all-templates/solid/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_svelte_mfe
          path: ./examples/all-templates/svelte/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_vanilla_mfe
          path: ./examples/all-templates/vanilla/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_all_templates_vue_mfe
          path: ./examples/all-templates/vue/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_react_mfe
          path: ./examples/communication-mfe-iframe/react-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_svelte_iframe
          path: ./examples/communication-mfe-iframe/svelte-iframe/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_counter_react_mfe
          path: ./examples/communication-mfe-mfe/react-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_counter_svelte_mfe
          path: ./examples/communication-mfe-mfe/svelte-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_import_maps
          path: ./examples/mfe-import-maps/react-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_routing_react
          path: ./examples/routing-mfe/react-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_routing_svelte
          path: ./examples/routing-mfe/svelte-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_storage_react
          path: ./examples/storage/react-microfrontend/dist
      - uses: actions/upload-artifact@master
        with:
          name: build_next_js
          path: ./examples/next-js/nextjs-blog/out
  build_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-doc
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Build doc
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_docusaurus
          path: ./build
  compose_files:
    runs-on: ubuntu-latest
    needs: [build_mfes, build_docusaurus]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build_docusaurus
          path: ./build
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_angular_mfe
          path: ./build/all-templates-angular-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_preact_mfe
          path: ./build/all-templates-preact-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_react_mfe
          path: ./build/all-templates-react-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_solid_mfe
          path: ./build/all-templates-solid-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_svelte_mfe
          path: ./build/all-templates-svelte-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_vanilla_mfe
          path: ./build/all-templates-vanilla-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_all_templates_vue_mfe
          path: ./build/all-templates-vue-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_react_mfe
          path: ./build/communication-react-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_svelte_iframe
          path: ./build/communication-svelte-iframe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_counter_react_mfe
          path: ./build/communication-counter-react-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_counter_svelte_mfe
          path: ./build/communication-counter-svelte-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_import_maps
          path: ./build/react-import-maps
      - uses: actions/download-artifact@master
        with:
          name: build_routing_react
          path: ./build/react-routing
      - uses: actions/download-artifact@master
        with:
          name: build_routing_svelte
          path: ./build/svelte-routing
      - uses: actions/download-artifact@master
        with:
          name: build_storage_react
          path: ./build/storage
      - uses: actions/download-artifact@master
        with:
          name: build_next_js
          path: ./build/next-js
      - uses: actions/upload-artifact@master
        with:
          name: pages-artifact
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: compose_files
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: pages-artifact
          path: ./build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
