name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build_communication_react_mfe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Build mfe
        working-directory: ./examples/communication-mfe-iframe/react-microfrontend
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_react_mfe
          path: ./examples/communication-mfe-iframe/react-microfrontend/dist
  build_communication_svelte_iframe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Build mfe
        working-directory: ./examples/communication-mfe-iframe/svelte-iframe
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_svelte_iframe
          path: ./examples/communication-mfe-iframe/svelte-iframe/dist
  build_communication_counter_react_mfe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Build mfe
        working-directory: ./examples/communication-mfe-mfe/react-microfrontend
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_counter_react_mfe
          path: ./examples/communication-mfe-mfe/react-microfrontend/dist
  build_communication_counter_svelte_mfe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Build mfe
        working-directory: ./examples/communication-mfe-mfe/svelte-microfrontend
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_communication_counter_svelte_mfe
          path: ./examples/communication-mfe-mfe/svelte-microfrontend/dist
  build_import_map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-examples
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Build mfe
        working-directory: ./examples/mfe-import-maps/react-microfrontend
        run: pnpm i && pnpm build
      - uses: actions/upload-artifact@master
        with:
          name: build_import_maps
          path: ./examples/mfe-import-maps/react-microfrontend/dist
  build:
    runs-on: ubuntu-latest
    needs:
      - build_communication_react_mfe
      - build_communication_svelte_iframe
      - build_communication_counter_react_mfe
      - build_communication_counter_svelte_mfe
      - build_import_maps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: orchy-mfe/orchy-doc
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: latest
      - name: Build doc
        run: pnpm i && pnpm build
      - uses: actions/download-artifact@master
        with:
          name: build_communication_react_mfe
          path: ./build/communication-react-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_svelte_iframe
          path: ./build/communication-svelte-iframe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_counter_react_mfe
          path: ./build/communication-counter-react-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_communication_counter_svelte_mfe
          path: ./build/communication-counter-svelte-mfe
      - uses: actions/download-artifact@master
        with:
          name: build_import_maps
          path: ./build/react-import-maps
      - uses: actions/upload-artifact@master
        with:
          name: pages-artifact
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: pages-artifact
          path: ./build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
